### ISSUE TITLE
About Comments

### ISSUE THREAD

**Issue by Anillc** [Anillc/blog#1]
https://anillc.cn/about

**Comment by auqhjjqdo0** [comment]
鹿乃真可爱

**Comment by Anillc** [comment]
> @auqhjjqdo
> 鹿乃真可爱

\鹿乃/\鹿乃/\鹿乃/

**Comment by lijiakaijun** [comment]
~~呼，刚找了一堆“高速下载器”不只是为了拉黑证书，而且还是要教其他班怎么辨别（我现在就怕其他人乱下载然后又要我去弄╮(╯▽╰)╭）~~

话说回来，评论和Aplay还行

~~只不过我用电脑访问发现“© 2020 Anillc - Powered By Hexo And Merry”不是在正中间...看着就有点别扭~~

**Comment by Anillc** [comment]
> @lijiajunljj
> ~~呼，刚找了一堆“高速下载器”不只是为了拉黑证书，而且还是要教其他班怎么辨别（我现在就怕其他人乱下载然后又要我去弄╮(╯▽╰)╭）~~
> 
> 话说回来，评论和Aplay还行
> 
> ~~只不过我用电脑访问发现“© 2020 Anillc - Powered By Hexo And Merry”不是在正中间...看着就有点别扭~~

www，底部的播放器是利用了[MetingJS](https://github.com/metowolf/MetingJS)放的我歌单的歌，不过网易给我吞了一堆，只有剩下的一部分了  

footer的修改的话已经在计划之中了，之前就知道这个问题了，待会儿就改改XD

**Comment by Anillc** [comment]
> @lijiajunljj
> ~~呼，刚找了一堆“高速下载器”不只是为了拉黑证书，而且还是要教其他班怎么辨别（我现在就怕其他人乱下载然后又要我去弄╮(╯▽╰)╭）~~
> 
> 话说回来，评论和Aplay还行
> 
> ~~只不过我用电脑访问发现“© 2020 Anillc - Powered By Hexo And Merry”不是在正中间...看着就有点别扭~~

footer已经改了ww，播放器也移到上边去了XD

**Comment by lijiakaijun** [comment]
改了还行

**Comment by xiaozhedesu** [comment]
ww
